/* CareerArth AI — lightweight consultant review view */

const runId = location.pathname.split('/').pop();
const app = document.getElementById('app');
const esc = (s) => { const d = document.createElement('div'); d.textContent = s ?? ''; return d.innerHTML; };
const api = (path, body) => fetch(path, {
  method: body ? 'POST' : 'GET',
  headers: { 'Content-Type': 'application/json' },
  body: body ? JSON.stringify(body) : undefined,
}).then(async (r) => { const j = await r.json().catch(() => ({})); if (!r.ok) throw new Error(j.error || r.statusText); return j; });

const SECTIONS = [
  ['dimensionInsights', 'Dimension explanations'],
  ['strengths', 'Strengths'],
  ['risks', 'Risks'],
  ['tensions', 'Tensions'],
  ['careerPaths', 'Career paths'],
  ['skillGaps', 'Skill gaps'],
  ['ninetyDayPlan', '90-day plan'],
  ['discussWithConsultant', 'Consultation items'],
];

const decisions = {};   // section -> 'approved' | 'flagged' | 'rejected'
const notes = {};
const startedAt = Date.now();

function sectionBody(r, key) {
  const val = r[key];
  if (!Array.isArray(val)) return `<p>${esc(String(val))}</p>`;
  return val.map((x) => {
    if (typeof x === 'string') return `<p>• ${esc(x)}</p>`;
    const title = x.title ?? x.dimension ?? x.skill ?? x.phase ?? x.pathTitle ?? '';
    const body = x.detail ?? x.explanation ?? x.why ?? x.fitRationale ?? (x.actions ? x.actions.join(' · ') : '');
    const evidence = (x.evidence ?? []).join(', ');
    return `<div class="item"><h3 style="font-size:14px;">${esc(title)}</h3><p class="small">${esc(body)}</p>
      ${evidence ? `<p class="small muted">evidence: ${esc(evidence)}</p>` : ''}</div>`;
  }).join('');
}

function render(run) {
  const r = run.report;
  app.innerHTML = `
  <div class="card">
    <div class="eyebrow">Consultant review</div>
    <h1 style="font-size:24px;">${esc(run.fullName)} — Arth ${run.scores.overall} <span class="band band-${run.scores.overallBand}">${run.scores.overallBand}</span></h1>
    <p class="small muted" style="margin-top:6px;">
      Run ${esc(run.id)} · generated by <b>${esc(run.generator)}</b>${run.model ? ` (${esc(run.model)})` : ''} ·
      evidence lint: ${run.lint.ok ? `<span class="lint-ok">pass (${run.lint.checked} refs)</span>` : `<span class="lint-bad">${run.lint.issues.length} issue(s)</span>`} ·
      ${run.usage ? `~$${run.usage.estCostUsd} (${run.usage.inputTokens} in / ${run.usage.outputTokens} out)` : 'no LLM cost (mock)'}
      · <a href="/report/${esc(run.id)}" target="_blank">customer view →</a>
    </p>
    ${run.lint.issues.length ? `<div class="error-box" style="display:block;">Lint issues:<br>${run.lint.issues.map(esc).join('<br>')}</div>` : ''}
    ${run.coverageNote ? `<p class="small" style="margin-top:8px; color:#8a6d2f;"><b>Coverage:</b> ${esc(run.coverageNote)}</p>` : ''}
    <details class="sources" style="margin-top:10px;"><summary>Profile & scores (raw)</summary>
      <pre class="small" style="overflow-x:auto; background:var(--parchment); padding:12px; border-radius:8px; margin-top:8px;">${esc(JSON.stringify({ profile: run.profile, scores: run.scores }, null, 2))}</pre>
    </details>
  </div>

  <div class="card">
    <h2 style="font-size:18px;">Overall diagnosis <span class="small muted">(editable)</span></h2>
    <textarea id="edit-diagnosis" rows="4">${esc(run.fullReview?.editedOverallDiagnosis ?? r.overallDiagnosis)}</textarea>
    <h2 style="font-size:18px; margin-top:18px;">Next decision <span class="small muted">(editable)</span></h2>
    <textarea id="edit-decision" rows="3">${esc(run.fullReview?.editedNextDecision ?? r.nextDecision)}</textarea>
  </div>

  ${SECTIONS.map(([key, label]) => `
    <div class="card">
      <div style="display:flex; justify-content:space-between; align-items:center; flex-wrap:wrap; gap:8px;">
        <h2 style="font-size:17px;">${label}</h2>
        <div class="review-actions" data-section="${key}">
          <button data-d="approved">Approve</button>
          <button data-d="flagged">Flag</button>
          <button data-d="rejected">Reject</button>
        </div>
      </div>
      ${sectionBody(r, key)}
      <input type="text" placeholder="Note (optional)" data-note="${key}" style="margin-top:8px; font-size:13px;">
    </div>`).join('')}

  <div class="card">
    <h2 style="font-size:18px; margin-bottom:8px;">Submit review</h2>
    <div class="row">
      <div><label>Confidence in this analysis (1–5)</label>
        <select id="rv-confidence">${[1,2,3,4,5].map((n) => `<option ${n === 4 ? 'selected' : ''}>${n}</option>`).join('')}</select></div>
      <div><label>Review time (minutes)</label>
        <input type="number" id="rv-minutes" min="0" step="0.5" placeholder="auto-tracked; adjust if needed"></div>
      <div><label>Overall</label>
        <select id="rv-overall"><option value="approved">Approve for client</option><option value="needs-revision">Needs revision</option></select></div>
    </div>
    <label>Notes</label>
    <textarea id="rv-notes" rows="2" placeholder="What did you change and why? What would you not trust?"></textarea>
    <div class="error-box" id="rv-error"></div>
    <button class="btn btn-primary" id="rv-submit" style="margin-top:14px;">Submit review</button>
    <span class="small muted" id="rv-done" style="margin-left:12px;"></span>
  </div>`;

  document.querySelectorAll('.review-actions').forEach((el) => {
    el.querySelectorAll('button').forEach((b) => {
      b.addEventListener('click', () => {
        decisions[el.dataset.section] = b.dataset.d;
        el.querySelectorAll('button').forEach((x) => x.className = '');
        b.className = `sel-${b.dataset.d}`;
      });
    });
  });

  document.getElementById('rv-submit').addEventListener('click', async () => {
    document.querySelectorAll('[data-note]').forEach((i) => { if (i.value.trim()) notes[i.dataset.note] = i.value.trim(); });
    const minutesInput = document.getElementById('rv-minutes').value;
    const minutes = minutesInput !== '' ? parseFloat(minutesInput) : Math.round(((Date.now() - startedAt) / 60000) * 10) / 10;
    const payload = {
      reviewer: 'consultant',
      decisions: Object.entries(decisions).map(([section, decision]) => ({ section, decision, note: notes[section] })),
      editedOverallDiagnosis: document.getElementById('edit-diagnosis').value,
      editedNextDecision: document.getElementById('edit-decision').value,
      confidence: parseInt(document.getElementById('rv-confidence').value, 10),
      minutes,
      notes: document.getElementById('rv-notes').value.trim(),
      overall: document.getElementById('rv-overall').value,
    };
    try {
      await api(`/api/runs/${runId}/review`, payload);
      document.getElementById('rv-done').textContent = `Saved (${minutes} min recorded). Customer view now shows the reviewed version.`;
    } catch (e) {
      const box = document.getElementById('rv-error'); box.textContent = e.message; box.style.display = 'block';
    }
  });
}

api(`/api/runs/${runId}?view=review`).then(render).catch((e) => {
  app.innerHTML = `<div class="card"><h2>Run not found</h2><p class="muted">${esc(e.message)}</p></div>`;
});
